import type { ToeicVocabularySeed } from "@/db/seed-data/toeic-vocabulary";
import toeicVocabularyEntriesJson from "@/db/seed-data/toeic-vocabulary-entries.json";

/**
 * Curated TOEIC catalog seed (TSL ∩ EN–VI dictionary). Generated by
 * `scripts/import-toeic-from-en-vi-dict.py` — see
 * docs/research/toeic-vocabulary-import.md.
 *
 * Kept in a seed-only module so client imports of `TOEIC_TOPICS` /
 * attribution from `toeic-vocabulary.ts` do not pull ~1k JSON rows.
 */
export const toeicVocabularySeed =
  toeicVocabularyEntriesJson as ToeicVocabularySeed[];
