import type { VocabularySeed } from "@/db/seed-data/vocabulary";

/** Value stored on `vocabularies.catalog_source` for the TOEIC browse list. */
export const TOEIC_CATALOG_SOURCE = "toeic" as const;

export const TOEIC_TOPICS = [
  { id: "office", label: "Office & admin", labelVi: "Văn phòng" },
  { id: "hr", label: "Hiring & HR", labelVi: "Nhân sự" },
  { id: "sales", label: "Sales & finance", labelVi: "Kinh doanh" },
  { id: "logistics", label: "Logistics & ops", labelVi: "Vận hành" },
  { id: "meetings", label: "Meetings & comms", labelVi: "Họp & giao tiếp" },
  { id: "core", label: "Core TOEIC", labelVi: "Nền tảng" },
] as const;

export type ToeicTopicId = (typeof TOEIC_TOPICS)[number]["id"];

export type ToeicVocabularySeed = VocabularySeed & { topic: ToeicTopicId };

export function isToeicTopicId(value: string): value is ToeicTopicId {
  return TOEIC_TOPICS.some((topic) => topic.id === value);
}

export function toeicTopicLabel(topicId: string | null | undefined): string {
  const topic = TOEIC_TOPICS.find((item) => item.id === topicId);
  return topic ? `${topic.labelVi} · ${topic.label}` : "Other";
}

/**
 * Attribution for the curated lemma list (Browne & Culligan TSL 1.1).
 * Meanings / IPA / examples below are EnglishFlow originals (learner-facing VI).
 */
export const TOEIC_TSL_ATTRIBUTION = {
  name: "TOEIC Service List (TSL) 1.1",
  url: "https://www.newgeneralservicelist.org/new-general-service-list-project-20",
  licenseCode: "ATTRIBUTION_REQUIRED" as const,
  attributionText:
    "Lemma selection and easy-English glosses based on the TOEIC Service List (TSL) 1.1 by Browne, C. & Culligan, B. (2016), licensed under CC BY-SA 4.0. Cite: Browne, C., and Culligan, B. (2016). The TOEIC Service List. Retrieved from http://www.newgeneralservicelist.org. Vietnamese meanings for the curated MVP subset are EnglishFlow originals; meanings for the expanded TSL batch are machine-assisted translations of the official TSL glosses. IPA from open-dict-data/ipa-dict (MIT) where available.",
  sourceVersion: "TSL 1.1",
};

/**
 * MVP curated subset (~70 lemmas) drawn from TSL themes (office, HR, sales,
 * logistics). Words already in `vocabularySeed` are intentionally omitted so
 * the catalog unique index stays clean; reseeding only touches this set.
 */
export const toeicVocabularySeed: ToeicVocabularySeed[] = [
  // --- Office & administration ---
  {
    word: "accountant",
    pronunciation: "uh-KOWN-tuhnt",
    phonetic: "/əˈkaʊn.tənt/",
    partOfSpeech: "noun",
    meaning: "kế toán viên",
    exampleSentence: "The accountant prepared the monthly financial report.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "agenda",
    pronunciation: "uh-JEN-duh",
    phonetic: "/əˈdʒen.də/",
    partOfSpeech: "noun",
    meaning: "chương trình nghị sự",
    exampleSentence: "Please review the agenda before tomorrow's meeting.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "applicant",
    pronunciation: "AP-li-kuhnt",
    phonetic: "/ˈæp.lɪ.kənt/",
    partOfSpeech: "noun",
    meaning: "ứng viên, người nộp đơn",
    exampleSentence: "Each applicant must submit a résumé by Friday.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "authorize",
    pronunciation: "AW-thuh-ryz",
    phonetic: "/ˈɔː.θə.raɪz/",
    partOfSpeech: "verb",
    meaning: "ủy quyền, cho phép chính thức",
    exampleSentence: "Only managers can authorize overtime payments.",
    difficulty: "hard",
    topic: "office",
  },
  {
    word: "deadline",
    pronunciation: "DED-lyn",
    phonetic: "/ˈded.laɪn/",
    partOfSpeech: "noun",
    meaning: "hạn chót",
    exampleSentence: "We must finish the proposal before the deadline.",
    difficulty: "easy",
    topic: "office",
  },
  {
    word: "department",
    pronunciation: "dih-PART-muhnt",
    phonetic: "/dɪˈpɑːrt.mənt/",
    partOfSpeech: "noun",
    meaning: "phòng ban",
    exampleSentence: "She works in the marketing department.",
    difficulty: "easy",
    topic: "office",
  },
  {
    word: "document",
    pronunciation: "DOK-yuh-muhnt",
    phonetic: "/ˈdɒk.jə.mənt/",
    partOfSpeech: "noun",
    meaning: "tài liệu, văn bản",
    exampleSentence: "Please attach the signed document to your email.",
    difficulty: "easy",
    topic: "office",
  },
  {
    word: "headquarters",
    pronunciation: "HED-kwor-terz",
    phonetic: "/ˈhedˌkwɔːr.tərz/",
    partOfSpeech: "noun",
    meaning: "trụ sở chính",
    exampleSentence: "The company's headquarters is in Singapore.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "memo",
    pronunciation: "MEM-oh",
    phonetic: "/ˈmem.oʊ/",
    partOfSpeech: "noun",
    meaning: "bản ghi nhớ nội bộ",
    exampleSentence: "HR sent a memo about the new dress code.",
    difficulty: "easy",
    topic: "office",
  },
  {
    word: "personnel",
    pronunciation: "pur-suh-NEL",
    phonetic: "/ˌpɜːr.səˈnel/",
    partOfSpeech: "noun",
    meaning: "nhân sự, đội ngũ nhân viên",
    exampleSentence: "All personnel must complete safety training.",
    difficulty: "hard",
    topic: "office",
  },
  {
    word: "policy",
    pronunciation: "POL-uh-see",
    phonetic: "/ˈpɒl.ə.si/",
    partOfSpeech: "noun",
    meaning: "chính sách",
    exampleSentence: "The return policy allows exchanges within 30 days.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "procedure",
    pronunciation: "pruh-SEE-jer",
    phonetic: "/prəˈsiː.dʒər/",
    partOfSpeech: "noun",
    meaning: "quy trình",
    exampleSentence: "Follow the emergency procedure posted on the wall.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "supervise",
    pronunciation: "SOO-per-vyz",
    phonetic: "/ˈsuː.pər.vaɪz/",
    partOfSpeech: "verb",
    meaning: "giám sát",
    exampleSentence: "She will supervise the new trainees this month.",
    difficulty: "medium",
    topic: "office",
  },
  {
    word: "submit",
    pronunciation: "suhb-MIT",
    phonetic: "/səbˈmɪt/",
    partOfSpeech: "verb",
    meaning: "nộp, gửi (hồ sơ, báo cáo)",
    exampleSentence: "Please submit your timesheet every Friday.",
    difficulty: "easy",
    topic: "office",
  },
  {
    word: "update",
    pronunciation: "UP-dayt",
    phonetic: "/ʌpˈdeɪt/",
    partOfSpeech: "verb",
    meaning: "cập nhật",
    exampleSentence: "Could you update the client list this afternoon?",
    difficulty: "easy",
    topic: "office",
  },
  // --- Hiring & HR ---
  {
    word: "benefits",
    pronunciation: "BEN-uh-fits",
    phonetic: "/ˈben.ɪ.fɪts/",
    partOfSpeech: "noun",
    meaning: "phúc lợi (nhân viên)",
    exampleSentence: "Health insurance is one of our employee benefits.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "candidate",
    pronunciation: "KAN-di-duht",
    phonetic: "/ˈkæn.dɪ.dət/",
    partOfSpeech: "noun",
    meaning: "ứng viên",
    exampleSentence: "We interviewed three candidates for the role.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "colleague",
    pronunciation: "KOL-eeg",
    phonetic: "/ˈkɒl.iːɡ/",
    partOfSpeech: "noun",
    meaning: "đồng nghiệp",
    exampleSentence: "My colleague helped me finish the report.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "credentials",
    pronunciation: "kri-DEN-shuhlz",
    phonetic: "/krɪˈden.ʃəlz/",
    partOfSpeech: "noun",
    meaning: "bằng cấp, chứng chỉ chuyên môn",
    exampleSentence: "Please bring copies of your credentials to the interview.",
    difficulty: "hard",
    topic: "hr",
  },
  {
    word: "hire",
    pronunciation: "HYR",
    phonetic: "/haɪər/",
    partOfSpeech: "verb",
    meaning: "tuyển dụng",
    exampleSentence: "The firm plans to hire five more engineers.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "interview",
    pronunciation: "IN-ter-vyoo",
    phonetic: "/ˈɪn.tə.vjuː/",
    partOfSpeech: "noun",
    meaning: "buổi phỏng vấn",
    exampleSentence: "Her job interview is scheduled for Monday morning.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "overtime",
    pronunciation: "OH-ver-tym",
    phonetic: "/ˈoʊ.vər.taɪm/",
    partOfSpeech: "noun",
    meaning: "giờ làm thêm",
    exampleSentence: "Staff may request overtime during the busy season.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "payroll",
    pronunciation: "PAY-rohl",
    phonetic: "/ˈpeɪ.roʊl/",
    partOfSpeech: "noun",
    meaning: "bảng lương; bộ phận tính lương",
    exampleSentence: "Payroll processes salaries on the last day of each month.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "promote",
    pronunciation: "pruh-MOHT",
    phonetic: "/prəˈmoʊt/",
    partOfSpeech: "verb",
    meaning: "thăng chức; đẩy mạnh",
    exampleSentence: "The company will promote two team leads next quarter.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "qualify",
    pronunciation: "KWOL-uh-fy",
    phonetic: "/ˈkwɒl.ɪ.faɪ/",
    partOfSpeech: "verb",
    meaning: "đủ điều kiện, đạt chuẩn",
    exampleSentence: "You must qualify before applying for the senior role.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "recruit",
    pronunciation: "rih-KROOT",
    phonetic: "/rɪˈkruːt/",
    partOfSpeech: "verb",
    meaning: "tuyển mộ, thu hút nhân sự",
    exampleSentence: "We need to recruit bilingual customer-service staff.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "resign",
    pronunciation: "rih-ZYN",
    phonetic: "/rɪˈzaɪn/",
    partOfSpeech: "verb",
    meaning: "từ chức",
    exampleSentence: "He decided to resign after five years at the firm.",
    difficulty: "medium",
    topic: "hr",
  },
  {
    word: "salary",
    pronunciation: "SAL-uh-ree",
    phonetic: "/ˈsæl.ə.ri/",
    partOfSpeech: "noun",
    meaning: "lương tháng",
    exampleSentence: "The starting salary includes a performance bonus.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "staff",
    pronunciation: "STAF",
    phonetic: "/stæf/",
    partOfSpeech: "noun",
    meaning: "nhân viên (tập thể)",
    exampleSentence: "All staff must attend the fire drill.",
    difficulty: "easy",
    topic: "hr",
  },
  {
    word: "trainee",
    pronunciation: "tray-NEE",
    phonetic: "/ˌtreɪˈniː/",
    partOfSpeech: "noun",
    meaning: "thực tập sinh, người đang được đào tạo",
    exampleSentence: "Each trainee is paired with an experienced mentor.",
    difficulty: "medium",
    topic: "hr",
  },
  // --- Sales, finance & clients ---
  {
    word: "bargain",
    pronunciation: "BAR-guhn",
    phonetic: "/ˈbɑːr.ɡən/",
    partOfSpeech: "noun",
    meaning: "món hời; thỏa thuận giá",
    exampleSentence: "Those office chairs were a real bargain.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "client",
    pronunciation: "KLY-uhnt",
    phonetic: "/ˈklaɪ.ənt/",
    partOfSpeech: "noun",
    meaning: "khách hàng (doanh nghiệp)",
    exampleSentence: "Our biggest client renewed the contract today.",
    difficulty: "easy",
    topic: "sales",
  },
  {
    word: "commission",
    pronunciation: "kuh-MISH-uhn",
    phonetic: "/kəˈmɪʃ.ən/",
    partOfSpeech: "noun",
    meaning: "hoa hồng",
    exampleSentence: "Sales reps earn a 10% commission on each deal.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "competitor",
    pronunciation: "kuhm-PET-ih-ter",
    phonetic: "/kəmˈpet.ɪ.tər/",
    partOfSpeech: "noun",
    meaning: "đối thủ cạnh tranh",
    exampleSentence: "A new competitor opened a store downtown.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "contract",
    pronunciation: "KON-trakt",
    phonetic: "/ˈkɒn.trækt/",
    partOfSpeech: "noun",
    meaning: "hợp đồng",
    exampleSentence: "Please read the contract carefully before signing.",
    difficulty: "easy",
    topic: "sales",
  },
  {
    word: "deposit",
    pronunciation: "dih-POZ-it",
    phonetic: "/dɪˈpɒz.ɪt/",
    partOfSpeech: "noun",
    meaning: "tiền đặt cọc",
    exampleSentence: "A 20% deposit is required to reserve the venue.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "discount",
    pronunciation: "DIS-kownt",
    phonetic: "/ˈdɪs.kaʊnt/",
    partOfSpeech: "noun",
    meaning: "giảm giá",
    exampleSentence: "Members receive a 15% discount on all orders.",
    difficulty: "easy",
    topic: "sales",
  },
  {
    word: "estimate",
    pronunciation: "ES-ti-muht",
    phonetic: "/ˈes.tɪ.mət/",
    partOfSpeech: "noun",
    meaning: "báo giá ước tính",
    exampleSentence: "The contractor sent an estimate for the renovation.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "expense",
    pronunciation: "ik-SPENS",
    phonetic: "/ɪkˈspens/",
    partOfSpeech: "noun",
    meaning: "chi phí",
    exampleSentence: "Travel expenses must be approved in advance.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "forecast",
    pronunciation: "FOR-kast",
    phonetic: "/ˈfɔːr.kæst/",
    partOfSpeech: "noun",
    meaning: "dự báo",
    exampleSentence: "The sales forecast looks strong for next quarter.",
    difficulty: "hard",
    topic: "sales",
  },
  {
    word: "invoice",
    pronunciation: "IN-voys",
    phonetic: "/ˈɪn.vɔɪs/",
    partOfSpeech: "noun",
    meaning: "hóa đơn thanh toán",
    exampleSentence: "Please pay the invoice within 14 days.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "negotiate",
    pronunciation: "nih-GOH-shee-ayt",
    phonetic: "/nɪˈɡoʊ.ʃi.eɪt/",
    partOfSpeech: "verb",
    meaning: "đàm phán",
    exampleSentence: "We will negotiate the price with the supplier.",
    difficulty: "hard",
    topic: "sales",
  },
  {
    word: "quote",
    pronunciation: "KWOHT",
    phonetic: "/kwoʊt/",
    partOfSpeech: "noun",
    meaning: "báo giá",
    exampleSentence: "Can you send me a quote for 500 units?",
    difficulty: "easy",
    topic: "sales",
  },
  {
    word: "retail",
    pronunciation: "REE-tayl",
    phonetic: "/ˈriː.teɪl/",
    partOfSpeech: "noun",
    meaning: "bán lẻ",
    exampleSentence: "She has ten years of experience in retail.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "revenue",
    pronunciation: "REV-uh-noo",
    phonetic: "/ˈrev.ə.njuː/",
    partOfSpeech: "noun",
    meaning: "doanh thu",
    exampleSentence: "Annual revenue rose by 8% last year.",
    difficulty: "hard",
    topic: "sales",
  },
  {
    word: "warranty",
    pronunciation: "WOR-uhn-tee",
    phonetic: "/ˈwɒr.ən.ti/",
    partOfSpeech: "noun",
    meaning: "bảo hành",
    exampleSentence: "The laptop comes with a two-year warranty.",
    difficulty: "medium",
    topic: "sales",
  },
  {
    word: "withdraw",
    pronunciation: "with-DRAW",
    phonetic: "/wɪðˈdrɔː/",
    partOfSpeech: "verb",
    meaning: "rút (tiền); rút lại",
    exampleSentence: "You can withdraw cash from any branch ATM.",
    difficulty: "medium",
    topic: "sales",
  },
  // --- Logistics, facilities & operations ---
  {
    word: "assemble",
    pronunciation: "uh-SEM-buhl",
    phonetic: "/əˈsem.bəl/",
    partOfSpeech: "verb",
    meaning: "lắp ráp; tập hợp",
    exampleSentence: "Workers assemble the devices on the production line.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "deliver",
    pronunciation: "dih-LIV-er",
    phonetic: "/dɪˈlɪv.ər/",
    partOfSpeech: "verb",
    meaning: "giao hàng",
    exampleSentence: "We deliver orders within three business days.",
    difficulty: "easy",
    topic: "logistics",
  },
  {
    word: "distribute",
    pronunciation: "dih-STRIB-yoot",
    phonetic: "/dɪˈstrɪb.juːt/",
    partOfSpeech: "verb",
    meaning: "phân phối",
    exampleSentence: "The warehouse distributes goods to regional stores.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "facility",
    pronunciation: "fuh-SIL-uh-tee",
    phonetic: "/fəˈsɪl.ə.ti/",
    partOfSpeech: "noun",
    meaning: "cơ sở, nhà xưởng/tiện ích",
    exampleSentence: "The new factory is a state-of-the-art facility.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "freight",
    pronunciation: "FRAYT",
    phonetic: "/freɪt/",
    partOfSpeech: "noun",
    meaning: "hàng hóa vận chuyển; cước vận tải",
    exampleSentence: "Freight costs increased due to higher fuel prices.",
    difficulty: "hard",
    topic: "logistics",
  },
  {
    word: "inventory",
    pronunciation: "IN-vuhn-tor-ee",
    phonetic: "/ˈɪn.vən.tɔːr.i/",
    partOfSpeech: "noun",
    meaning: "hàng tồn kho",
    exampleSentence: "We need to check the inventory before restocking.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "launch",
    pronunciation: "LAWNCH",
    phonetic: "/lɔːntʃ/",
    partOfSpeech: "verb",
    meaning: "ra mắt (sản phẩm)",
    exampleSentence: "The company will launch the new app in June.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "maintain",
    pronunciation: "mayn-TAYN",
    phonetic: "/meɪnˈteɪn/",
    partOfSpeech: "verb",
    meaning: "duy trì, bảo trì",
    exampleSentence: "Technicians maintain the machines every week.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "manufacture",
    pronunciation: "man-yuh-FAK-cher",
    phonetic: "/ˌmæn.jəˈfæk.tʃər/",
    partOfSpeech: "verb",
    meaning: "sản xuất (công nghiệp)",
    exampleSentence: "The plant manufactures electronic components.",
    difficulty: "hard",
    topic: "logistics",
  },
  {
    word: "merchandise",
    pronunciation: "MUR-chuhn-dys",
    phonetic: "/ˈmɜːr.tʃən.daɪs/",
    partOfSpeech: "noun",
    meaning: "hàng hóa (để bán)",
    exampleSentence: "Damaged merchandise cannot be returned to shelves.",
    difficulty: "hard",
    topic: "logistics",
  },
  {
    word: "occupy",
    pronunciation: "OK-yuh-py",
    phonetic: "/ˈɒk.jə.paɪ/",
    partOfSpeech: "verb",
    meaning: "chiếm dụng, sử dụng (không gian)",
    exampleSentence: "The new team will occupy the third-floor offices.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "operate",
    pronunciation: "OP-uh-rayt",
    phonetic: "/ˈɒp.ə.reɪt/",
    partOfSpeech: "verb",
    meaning: "vận hành, điều hành",
    exampleSentence: "Only trained staff may operate this equipment.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "shipment",
    pronunciation: "SHIP-muhnt",
    phonetic: "/ˈʃɪp.mənt/",
    partOfSpeech: "noun",
    meaning: "lô hàng",
    exampleSentence: "The shipment arrived two days earlier than expected.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "supplier",
    pronunciation: "suh-PLY-er",
    phonetic: "/səˈplaɪ.ər/",
    partOfSpeech: "noun",
    meaning: "nhà cung cấp",
    exampleSentence: "We switched to a local supplier to cut costs.",
    difficulty: "medium",
    topic: "logistics",
  },
  {
    word: "warehouse",
    pronunciation: "WAIR-hows",
    phonetic: "/ˈweər.haʊs/",
    partOfSpeech: "noun",
    meaning: "kho hàng",
    exampleSentence: "Extra stock is stored in the west warehouse.",
    difficulty: "medium",
    topic: "logistics",
  },
  // --- Meetings & communication ---
  {
    word: "attend",
    pronunciation: "uh-TEND",
    phonetic: "/əˈtend/",
    partOfSpeech: "verb",
    meaning: "tham dự",
    exampleSentence: "All managers must attend the quarterly review.",
    difficulty: "easy",
    topic: "meetings",
  },
  {
    word: "conference",
    pronunciation: "KON-fer-uhns",
    phonetic: "/ˈkɒn.fər.əns/",
    partOfSpeech: "noun",
    meaning: "hội nghị",
    exampleSentence: "She presented our results at an industry conference.",
    difficulty: "medium",
    topic: "meetings",
  },
  {
    word: "notify",
    pronunciation: "NOH-ti-fy",
    phonetic: "/ˈnoʊ.tɪ.faɪ/",
    partOfSpeech: "verb",
    meaning: "thông báo",
    exampleSentence: "Please notify IT if you change your password.",
    difficulty: "medium",
    topic: "meetings",
  },
  {
    word: "request",
    pronunciation: "rih-KWEST",
    phonetic: "/rɪˈkwest/",
    partOfSpeech: "verb",
    meaning: "yêu cầu",
    exampleSentence: "You can request a meeting through the portal.",
    difficulty: "easy",
    topic: "meetings",
  },
  {
    word: "survey",
    pronunciation: "SER-vay",
    phonetic: "/ˈsɜːr.veɪ/",
    partOfSpeech: "noun",
    meaning: "khảo sát",
    exampleSentence: "Please complete the customer satisfaction survey.",
    difficulty: "easy",
    topic: "meetings",
  },
  {
    word: "tentative",
    pronunciation: "TEN-tuh-tiv",
    phonetic: "/ˈten.tə.tɪv/",
    partOfSpeech: "adjective",
    meaning: "tạm thời, chưa chắc chắn",
    exampleSentence: "We set a tentative date for the product demo.",
    difficulty: "hard",
    topic: "meetings",
  },
  {
    word: "transfer",
    pronunciation: "trans-FUR",
    phonetic: "/trænsˈfɜːr/",
    partOfSpeech: "verb",
    meaning: "chuyển (người, tiền, dữ liệu)",
    exampleSentence: "HR will transfer her to the Seoul office next month.",
    difficulty: "medium",
    topic: "meetings",
  },
  {
    word: "available",
    pronunciation: "uh-VAY-luh-buhl",
    phonetic: "/əˈveɪ.lə.bəl/",
    partOfSpeech: "adjective",
    meaning: "có sẵn; rảnh",
    exampleSentence: "Is the meeting room available at 3 p.m.?",
    difficulty: "easy",
    topic: "meetings",
  },
  {
    word: "expand",
    pronunciation: "ik-SPAND",
    phonetic: "/ɪkˈspænd/",
    partOfSpeech: "verb",
    meaning: "mở rộng",
    exampleSentence: "The chain plans to expand into three new cities.",
    difficulty: "medium",
    topic: "meetings",
  },
  {
    word: "figure",
    pronunciation: "FIG-yer",
    phonetic: "/ˈfɪɡ.jər/",
    partOfSpeech: "noun",
    meaning: "con số (thống kê)",
    exampleSentence: "Sales figures improved after the campaign.",
    difficulty: "easy",
    topic: "meetings",
  },
];
