import type { QuizSeed } from "@/db/seed-data/quizzes";
import generatedVocabQuizzesJson from "@/db/seed-data/vocab-quizzes.generated.json";

type GeneratedVocabQuizFile = {
  generatedBy: string;
  quizzes: QuizSeed[];
};

/**
 * Vocabulary quizzes generated by `scripts/import-vocab-quizzes.py`
 * (`npm run quiz:import-vocab`). Seed-only — do not import from client
 * features (keeps the JSON out of the browser bundle).
 *
 * Slugs are prefixed `vocab-generated-` so they never collide with
 * `coursePracticeQuizzes` / grammar / listening quiz slugs.
 */
const generatedFile = generatedVocabQuizzesJson as GeneratedVocabQuizFile;

export const generatedVocabQuizzes: QuizSeed[] = Array.isArray(generatedFile.quizzes)
  ? generatedFile.quizzes
  : [];
